apiVersion : apps/v1
kind: Deployment
metadata:
  name: demoangularimage
  labels:
    app: demoangularimage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demoangularimage
  template:
    metadata:
      labels:
        app: demoangularimage 
    spec:
      containers:
        - name: demoangularimage 
          image: jccontainerreg.azurecr.io/demoangularimage
          ports:
          - containerPort: 80
