apiVersion : apps/v1
kind: Deployment
metadata:
  name: essjceemyangularapp
  labels:
    app: essjceemyangularapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: essjceemyangularapp
  template:
    metadata:
      labels:
        app: essjceemyangularapp 
    spec:
      containers:
        - name: essjceemyangularapp 
          image: jccontainerreg.azurecr.io/essjceemyangularapp
          ports:
          - containerPort: 80
