apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: essjceemyangularapp 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: essjceemyangularapp 
    spec:
      containers:
        - name: essjceemyangularapp 
          image: jccontainerreg.azurecr.io/essjceemyangularapp
          ports:
          - containerPort: 80